### ISSUE TITLE
Add compatibility to node 16.x

### ISSUE THREAD

**Issue by adi-li** [VGLoic/metamask-react#11]
`react` is the only `peer-dependencies` of this package, and it should work fine with node 16.x.
However, the package only supports `node ^12 || ^14 || ^15` stated in `package.json`.
I guess it is because one of the `devDependencies` (`eth-testing`) require such condition.

I suggest changing this package to build the distribution files during the CI phase, and change the `engines` to `devEngines`, so that we can support any node version that `react` support.

**Comment by VGLoic** [comment]
Sorry for the late answer @adi-li !

Thanks a lot for this issue!

To be honest I can't really remember why I limited to specific node versions in the first place (same goes for `eth-testing`).
Even in terms of local development there is no particular need, at least for now, to restrict the node version.

I will remove it from `eth-testing` and here

Don't hesitate to tell me if you see some particular reasons why it might be useful to keep it in `devEngines` :)

**Comment by adi-li** [comment]
Thanks @VGLoic
