### ISSUE TITLE
Love the package

### ISSUE THREAD

**Issue by forgowhisky** [VGLoic/metamask-react#17]
Not an issue. I just wanted to voice my support for this package!
It's extremely easy to use after spending hours setting this up manually with an abundance of @ts-ginore's, this was a welcomed alternative.

Hopefully more people discover this!

(is there a better place for me to leave a comment or review?? lol)

**Comment by VGLoic** [comment]
Damn @forgowhisky, thank you so much for this comment, that means a lot to me :)

Do not hesitate to share any way how I can improve this package!

**Comment by forgowhisky** [comment]
no problem @VGLoic !

We are using it for some enterprise sports betting software right now, so I will also be sure to share it in our listed public dependencies.

**Comment by VGLoic** [comment]
I'm closing the issue but thanks again for the comment @forgowhisky!
