### ISSUE TITLE
Disconnect Wallet

### ISSUE THREAD

**Issue by coreycross524** [VGLoic/metamask-react#20]
Hey there, sorry if this is a stupid question. 

Is there anyway to disconnect the users wallet? or do they have to do that in their metamask. If someone uses multiple wallets I can see the integration detects the wallet change. but I'd love to be able to send them back to the start.

Thanks alot!

P.s Amazing work, you've saved me hours of work! you're awesome!!

**Comment by VGLoic** [comment]
Hey @coreycross524! Do you think we can close this issue or do you want to discuss this topic a bit further? :)

**Comment by VGLoic** [comment]
Closing the issue for inactivity, @coreycross524 feel free to reopen it if needed :)
