### ISSUE TITLE
Metamask conflicts with Coinbase wallet extension

### ISSUE THREAD

**Issue by olekon** [VGLoic/metamask-react#33]
### What version of React and MetaMask-React are you using?

- React: 17.02
- MetaMask-React: 2.1.2
(but problem presents in 2.4.0 as well)

### What is the current behavior?

It seems that `metamask-provider` picks a wrong version of `window.ethereum` object if there are several wallet extensions. In my case it is Metamask and Coinbase wallet.

The problem is in this line 

```
const ethereum = (window as WindowInstanceWithEthereum).ethereum;
```

It is the same in every function of provider: 
- synchronize
- subsribeToAccountsChanged
- subscribeToChainChanged
- requestAccounts
- addEthereumChain
- switchEthereumChain
- `ethereum: isAvailable
        ? (window as WindowInstanceWithEthereum).ethereum
        : null,`

I guess it should be rewritten as something like
```
const getMetamaskProvider = () => {
  if(!window.ethereum?.providers) {
    return window.ethereum;
  }
  return window.ethereum.providers.find(p => p.isMetaMask)
}
...

async function synchronize(dispatch: (action: Action) => void) {
  const ethereum = getMetamaskProvider();
  ...
}
```

### What is the expected behavior?

Metamask-provider should pick ethereum provider with `isMetaMask` property

**Comment by VGLoic** [comment]
Hey @olekon! Thanks a lot for this issue!

I was not aware that Coinbase Wallet extension was also using the `ethereum` field of the `window`, so thanks a ton!

I'm working on a fix :)

**Comment by VGLoic** [comment]
@olekon the PR #34 should solve the issue, if you have the time don't hesitate to review it 

Otherwise I will merge the PR in ~20 hours :)

**Comment by olekon** [comment]
Thank you so much!
