### ISSUE TITLE
Manually connect to site doesn't trigger account and status update

### ISSUE THREAD

**Issue by EugeneSnikhovskiy** [VGLoic/metamask-react#37]
### What version of React and MetaMask-React are you using?

- React: 18.2.0
- MetaMask-React: 2.4.1

### What is the current behavior?

```ts
const { account, connect, status } = useMetaMask();
```

connect method works correctly and update account and status, but when I open metamask extension in chrome and choose manual connect to current site - account and status is still has ```null/"notConnected"``` values

### What is the expected behavior?

Manual connection to site should trigger update for account and status values

**Comment by VGLoic** [comment]
@EugeneSnikhovskiy! Thanks a lot for this issue!

I did not know this option in MetaMask! I'm gonna try to take a look this week-end :)

**Comment by EugeneSnikhovskiy** [comment]
Wow. This is so cool. Thank you so much for really fast support :)
