### ISSUE TITLE
Adding MetaMaskProvider throws Invalid hook call

### ISSUE THREAD

**Issue by mrv777** [VGLoic/metamask-react#40]
### What version of React and MetaMask-React are you using?

- React: 18.2 & Next.JS 13.1
- MetaMask-React: 2.6

### What is the current behavior?

As soon as I add the provider:
```
<MetaMaskProvider>
          <main className={stabilFont.className}>
            <Content Component={Component} pageProps={pageProps} />
          </main>
        </MetaMaskProvider>
```

 it throws this error for any page in the app

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. 
```

Removing the wrapping tags `<MetaMaskProvider>...</MetaMaskProvider>` and everything is good again

### What is the expected behavior?

No error 😃

**Comment by VGLoic** [comment]
Hey @mrv777 ! Thanks a lot for this issue :)

I'm taking a look as fast as possible!

In the meantime, would it be possible for you to share with me more info on your code? Like how the `useMetaMask` hook is used? 🙏

**Comment by mrv777** [comment]
The `useMetaMask` isn't actually needed to even throw the error.  Just having the Provider added alone is enough to throw the error.

It was also suggested I double check that `MetaMaskProvider` is in the root of the app in a parent component.  Unfortunately I will be away for the rest of the day and have to take a look late tomorrow.  If that fixes it, I will make sure to comment it here too.

Also, thanks for such a quick acknowledgment!

**Comment by VGLoic** [comment]
Happy to continue the discussion on this when you can :)

I tried in a codesandbox with Next@13.1.6 and metamask-react@2.6.0 and I don't have issue for now, here is the link to the codesandbox -> [link](https://codesandbox.io/p/sandbox/competent-morning-r1hi4u?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A15%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A15%7D%5D)

I also saw that using the `app` directory beta of Next.js, there is a need to explicitly say that we are in a client component when using client side code (e.g. React state or context) with the `'use client'` directive, you can find more details on [their doc](https://beta.nextjs.org/docs/rendering/server-and-client-components) :)

**Comment by mrv777** [comment]
Hmm, it must be some conflict with something else.  If I have `const { status, connect, account } = useMetaMask();` or `import { MetaMaskProvider } from "metamask-react";` I get an `Invalid Hook` error

**Comment by VGLoic** [comment]
Would it be possible that you share more code? Or is the repository public? :)

I'm happy to help on this!
