### ISSUE TITLE
When `switchNetwork` with unknown chain, the function throws an exception with 4902 error code

### ISSUE THREAD

**Issue by serejke** [VGLoic/metamask-react#43]
### What is the new or updated feature that you are suggesting?

According to the Metamask [API](https://docs.metamask.io/wallet/reference/rpc-api/#returns-4) the `metamask.switchNetwork` throws the following exception if the specified chain is not installed in the user's Metamask configuration:
```
{
  "code": 4902,
  "message": "Unrecognized chain ID \"0x116e9\". Try adding the chain using wallet_addEthereumChain first.",
  "stack": "<app stack>"
}
```

https://github.com/VGLoic/metamask-react/blob/6e6b9a09c26e0c7e70809130492b12dc6ce78fe1/src/metamask-provider.tsx#L268

the `switchChain` has a signature `(chainId: string) => Promise<void>`. 

_Suggestion_: catch the exception inside the `switchChain` function and return `'unknownNetwork' | 'pending'`, and propagate the exception otherwise.

I believe this would make the API a bit clearer: the clients would `await` the result and on `unknownNetwork`, they need to call `addChain`.

### Why should this feature be included?

Make the API and documentation a bit clearer.

**Comment by VGLoic** [comment]
Hey @serejke! Thanks a lot for this issue!

I like the idea but I think it is more customary in the JavaScript/TypeScript ecosystem to have a throw when the method does not work as intended, I am a bit afraid that most of the developers will not be careful enough to deal with this new API

However, I would be happy to improve the documentation of the `switchChain` method in order to inform as much as possible developers of this particular error :)

**Comment by VGLoic** [comment]
Happy to have your feedbacks on #45 :)

**Comment by serejke** [comment]
The target network not being registered in MetaMask is a perfectly valid use case. The current function throws an exception without a documented structure (and actually, crashed my app in the tests). I know that there is `.code` to check on, but I had to add the following code. I imagine many users who want to handle this case properly will have something similar:

```
       try {
        await metamaskSwitchChain(targetNetwork)
      } catch (e) {
        // If the network is unknown (https://docs.metamask.io/wallet/reference/rpc-api/#returns-4)
        if (e.code === 4902) {
          const chain = findChainById(targetNetwork)
          if (!chain) {
            console.error(`Unknown chain ${targetNetwork}`)
            return Promise.resolve()
          }
          try {
            await metamaskAddChain({
              chainId: chain.chainId,
              chainName: chain.chainName,
              nativeCurrency: {
                name: chain.nativeCurrency.name,
                symbol: chain.nativeCurrency.symbol,
                decimals: chain.nativeCurrency.decimals,
              },
              rpcUrls: chain.rpcUrls,
              blockExplorerUrls: chain.blockExplorerUrls,
            })
          } catch (e) {
            console.error('Failed to add MetaMask network', e)
          }
        } else {
          console.error(
            `Failed to switch Metamask network to ${targetNetwork}`,
            e,
          )
        }
      }
    }
```

**Comment by VGLoic** [comment]
Yes I agree with you that it is painful 😁 but it is the "best option" offered by the MetaMask API at the moment

Ideally in our case, MetaMask would expose a helper to check if a chain has been added, but this is not the case for now.

The primary goal of this package is to be as close as possible from the MetaMask API, but I try as much as I can to not deviate from it and add layers over it. I want to encourage people to go check the MetaMask doc if they need something and I don't want to maintain another documentation on top of MetaMask 😁.

If we take your example and we try to keep the return type as `Promise<void>`, what would be your desired target in terms of code? 🤔

**Comment by serejke** [comment]
I see. Having a minimalistic React wrapper over MetaMask state is reasonable. This feature request is one-time gotcha, which should become less painful for newcomers thanks to the updated documentation. We can close this task then, and see if anyone hits the same problem.

> If we take your example and we try to keep the return type as Promise<void>, what would be your desired target in terms of code? 🤔
With `Promise<void>` I don't think the code will be more readable.
`void` replaced with a return enum might be better to iterate by all possible results (think pattern matching)

**Comment by VGLoic** [comment]
Thanks a lot for these inputs, I appreciate it :)

> It's more about developer not forgetting to handle this case than the amount of code

It's a very good point, I just think the JavaScript / TypeScript ecosystem is not yet very used to this kind of pattern compared to other languages and I prefer to stick with the dummy extension of MetaMask API for now. Ideally I would love to see this kind of change at the MetaMask level.

In any case, happy to re-open the issue at some point if more people need this feature :)
