### ISSUE TITLE
Handle `on('disconnect')` event

### ISSUE THREAD

**Issue by serejke** [VGLoic/metamask-react#44]
### What is the new or updated feature that you are suggesting?

MetaMask documents a `disconnect` event: https://docs.metamask.io/wallet/reference/provider-api/#disconnect

which seemingly happens only in case of network connectivity issues.

I don't have a specific reproducible case in mind, but maybe the `MetaMaskProvider` could subscribe to that event and update the state accordingly.

### Why should this feature be included?

Handle disconnection error properly

**Comment by VGLoic** [comment]
Thanks for this other issue @serejke!

It looks interesting indeed! I think a new field `rpcProviderConnected` in the state may be interesting to add in order to track the health of the underlying RCP provider

I'm currently in holidays but I'll take a look in the coming weeks :)

**Comment by VGLoic** [comment]
Hey!

Sorry for the late news, I did not take the time to work on this!

Unfortunately I am no longer maintaining this package so I'll close this issue. I linked the alternatives in the README.

Thanks again for this issue! Have a great day!
