### ISSUE TITLE
MetaMaskProvider error when both metamask and core|crypto wallet extension is used

### ISSUE THREAD

**Issue by rajpraful** [VGLoic/metamask-react#48]
### What version of React and MetaMask-React are you using?

- React: 18.2.0
- MetaMask-React: 2.4.1
- Yarn: 1.22.22
- Node: 18.19.0

### What is the current behavior?

Whole is not rendered because of error in provider

metamask-provider.js:155 Uncaught TypeError: ethereum.on is not a function
    at subscribeToChainChanged (metamask-provider.js:155:1)

### What is the expected behavior?

Should work with multiple extensions

**Comment by VGLoic** [comment]
Hey @rajpraful !

Thanks a lot for this issue! What is the `core|crypto wallet extension` please?

Also, the retrieval of the `ethereum` provider is not perfect but efforts have been spent to deal with multiple providers and correctly identifying the MetaMask one. It could be argue that this extension is badly trying to impersonate the MetaMask provider 🤔

**Comment by rajpraful** [comment]
https://chromewebstore.google.com/detail/core-crypto-wallet-nft-ex/agoakfejjabomempkjlepdflaleeobhb

A  chrome extension to connect to wallet

**Comment by VGLoic** [comment]
I still see this as `beta` and I don't see any GitHub so it would be too costly on my side to identify if the issue is on the side of the extension or on the side of this package :(

I would gladly take a GitHub for the codebase if you have one available :)
