### ISSUE TITLE
example improvement?

### ISSUE THREAD

**Issue by Gresliebear** [VGLoic/metamask-react#6]
is this the correct import?

import MetaMaskProvider from 'metamask-react';

×
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

*** Fixed it *** 

import {MetaMaskProvider} from 'metamask-react';

import {useMetaMask} from 'metamask-react'

**Comment by VGLoic** [comment]
Hey! Thanks a lot for reporting the issue!

There is not default export indeed, only named exports :)

I'm gonna update the example part in the README in order to clarify that

**Comment by Gresliebear** [comment]
Also thank you for making a great library I appreciate it makes testing easier for Dapps
